import type { Metadata } from "next";
import { Inter ,Roboto} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter =Roboto(
  {
    weight: ["400", "700"],
    subsets: ["latin"],
    display: "swap",}
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${inter.className} bg-gray-950 text-white `}>
      <Navbar />
      {children}
      </body>
    </html>
  );
}
